### ISSUE TITLE
Skyscraper4x4 Entwurf

### ISSUE THREAD

**Issue by timruhkopf** [timruhkopf/Codewars#1]
positions of informationsets:
where each number is the index of clue.
(0,11),(1,10), (2,9), (3,8) # columnwise
(4,15),(5,14),(6,13),(7,12) # rowwise

gegeben clueindecies -> info of clue, consider the info sets (0,1,2,3,4)
that is the clue given and the tupels resulting from that info
bei column ist das zweite infoset reversed, bei row das erste: da man von oben nach unten und von links nach rechts liest.
column: {tupels of first condition & reversed tupels of second conditon}
row : vice versa.

now pixel-wise look at the values of the sets with row & columns!
depending on the amount of info in those sets, replace those values that are certain and update the row & column sets
again look at those that are certain.
Or Bruteforcing.

**Comment by TiStat** [comment]
Issue is the last part: iteratively expensive. particular, if upscaling 7x7
